{{- define "dbcall.corezoid_dbcall.resources" }}
{{- if .Values.global.dbcall.corezoid_dbcall.resources }}
{{- $resources := .Values.global.dbcall.corezoid_dbcall.resources }}
resources:
{{ $resources | toYaml | trim | indent 4 }}
{{- else }}
resources:
  limits:
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 200Mi
{{- end }}
{{- end }}
