apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-headless-service
  labels:
    {{- include "dbcall.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "dbcall.labels" . | nindent 6 }}
  ports:
  - port: {{ .Values.metricsPort }}
    targetPort: {{ .Values.metricsPort }}
    protocol: TCP
    name: monitoring
