apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-cpu-autoscale
  labels:
    {{- include "dbcall.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  {{- if and .Values.global.corezoid_dbcall.minReplicas .Values.global.corezoid_dbcall.maxReplicas }}
  minReplicas: {{ .Values.global.corezoid_dbcall.minReplicas }}
  maxReplicas: {{ .Values.global.corezoid_dbcall.maxReplicas }}
  {{- else if and .Values.scale.minReplicas .Values.scale.maxReplicas }}
  minReplicas: {{ .Values.scale.minReplicas }}
  maxReplicas: {{ .Values.scale.maxReplicas }}
  {{- else }}
  minReplicas: 2
  maxReplicas: 10
  {{- end }}
  {{- if .Values.scale.targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage: {{ .Values.scale.targetCPUUtilizationPercentage }}
  {{- end }}
