{{- if .Values.global.db.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.db.secret.name}}
  labels:
    {{- include "dbcall.labels" . | nindent 4 }}
    tier: "postgres"
type: Opaque
data:
  {{- range $key, $value := .Values.global.db.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end}}
