{{- if .Values.global.mq.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbcall.rabbitSecretName" . | quote }}
  labels:
    {{- include "dbcall.labels" . | nindent 4 }}
    tier: "rabbitmq"
type: Opaque
data:
  {{- range $key, $value := .Values.global.mq.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end}}
