apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dbcall-service
  labels:
    release: {{ .Release.Name | quote }}
    app: {{ .Values.helm.app | quote }}
    tier: {{ .Values.helm.tier | quote }}
spec:
  type: NodePort
  selector:
    release: {{ .Release.Name | quote }}
    app: {{ .Values.helm.app | quote }}
    tier: {{ .Values.helm.tier | quote }}
  ports:
  - protocol: TCP
    port: {{ .Values.config.api.server.port }}
    targetPort: {{ .Values.config.api.server.port }}
